
const problemlist = [
    {
        list1: `
        <ul class="task-list"><li class="task"><a href="/problemset/task/1068">Weird Algorithm</a><span class="detail">83005 / 86880</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/1083">Missing Number</a><span class="detail">70351 / 74322</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/1069">Repetitions</a><span class="detail">61404 / 64456</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/1094">Increasing Array</a><span class="detail">57171 / 59701</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/1070">Permutations</a><span class="detail">50341 / 52044</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/1071">Number Spiral</a><span class="detail">35664 / 38879</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/1072">Two Knights</a><span class="detail">26649 / 27593</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/1092">Two Sets</a><span class="detail">28790 / 31271</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/1617">Bit Strings</a><span class="detail">33697 / 35625</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/1618">Trailing Zeros</a><span class="detail">31483 / 33725</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/1754">Coin Piles</a><span class="detail">27682 / 30558</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/1755">Palindrome Reorder</a><span class="detail">25225 / 26941</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/2205">Gray Code</a><span class="detail">15127 / 17293</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/2165">Tower of Hanoi</a><span class="detail">14175 / 14798</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/1622">Creating Strings</a><span class="detail">21880 / 22547</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/1623">Apple Division</a><span class="detail">20940 / 24051</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/1624">Chessboard and Queens</a><span class="detail">12601 / 12865</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/2431">Digit Queries</a><span class="detail">8161 / 9830</span> <span class="task-score icon "></span></li><li class="task"><a href="/problemset/task/1625">Grid Paths</a><span class="detail">5248 / 6697</span> <span class="task-score icon "></span></li></ul>
        `
    }
]



export default problemlist